---
  - name: play Hello World
    hosts: default
    become: true

    tasks:
      - name: task Hello World
        shell:
          'echo "Hello World!\n$(cat /etc/centos-release)"'
        register:
          hello_world

      - debug: msg="{{ hello_world.stdout }}"

  - name: play Install Geerlingguy Docker
    hosts: default
    become: true
    vars:
      docker_edition: 'ce'
      docker_package: "docker-{{ docker_edition }}"
      docker_package_state: present
      docker_service_state: started
      docker_service_enabled: true
      docker_restart_handler_state: restarted
      docker_install_compose: true
      docker_compose_version: "1.26.0"
      docker_compose_path: /usr/local/bin/docker-compose
      docker_apt_release_channel: stable
      docker_apt_arch: amd64
      docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
      docker_apt_ignore_key_error: True
      docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      docker_users:
        - centos

    roles:
      - geerlingguy.docker
